### ISSUE TITLE
Use Sublime QML as reference?

### ISSUE THREAD

**Issue by machinekoder** [kropp/intellij-qml#12]
GitHub seems to use the [Sublime-QML](https://github.com/skozlovf/Sublime-QML/tree/e3e058a21f3c44d64ef5eda93925ee84169b62ec) plugin as a source for QML syntax highlighting. Maybe it could serve as a reference for fixing the issues.

**Comment by kropp** [comment]
Sublime-QML highlights syntax based on regexp patterns. It is easy to implement and fast in simple cases. IntelliJ-based IDEs usually take a different approach, namely to parse source code to AST and implement all the features on top of it. It is more difficult to implement, but allows to do much more in terms of features.

**Comment by machinekoder** [comment]
Yes, I'm aware of that. I just mean that it could serve as a reference for finding out the QML/JS keywords. For example take a look at: https://github.com/skozlovf/Sublime-QML/blob/e3e058a21f3c44d64ef5eda93925ee84169b62ec/Support/QML.tmLanguage#L250 which could be easily translated to the corresponding tokens in the `.flex` file.
