### ISSUE TITLE
Instructions how to the build project are missing

### ISSUE THREAD

**Issue by machinekoder** [kropp/intellij-qml#14]
It would be great if there would be a short description of how to compile the project with IntelliJ IDEA. 

Maybe including the `.idea` directory would help, but I personally don't like the idea of adding a developers configuration to the source code.

I tried to compile the plugin with the latest IDEA and JDK 1.8 shipped with the IDE, however, I got stuck with some Kotlin errors during compilation.

**Comment by kropp** [comment]
I'll add build instructions to the repo later, but in few words: import build.gradle in IDEA and then run `runIde` task from Gradle tool window.

**Comment by machinekoder** [comment]
Thanks, I got it.

I forgot to select the IntelliJ Plugin SDK as target build platform, which also got me through the build errors.

Then I selected the Gradle run/debug target with task `runIde` as you described.

**Comment by machinekoder** [comment]
Thanks
