### ISSUE TITLE
What's supported?

### ISSUE THREAD

**Issue by StefanFabian** [kropp/intellij-qml#2]
Hey there,

I couldn't find what exactly this plugin can do.
Is it only syntax highlighting or is autocomplete also supported?
If not, is support planned?

Best,
Stefan

**Comment by kropp** [comment]
Hi, to be honest not much is supported at the moment. Only syntax highlighting and preview with `qmlscene`. But support for additional features is planned, of course. No estimations though, stay tuned.

**Comment by StefanFabian** [comment]
Thank you for the quick answer.
How do I open the preview in CLion (2017.2.3)?

**Comment by kropp** [comment]
You need to manually create and setup "Qml Scene" Run Configuration. I'll provide autoconfiguration option later.

**Comment by StefanFabian** [comment]
Ah okay, I thought by preview you meant something like a WYSIWYG editor.
Thank you for your work on this plugin!
It may not support much yet but it's a lot better than plain text 👍
