### ISSUE TITLE
Currently doesn't work on CLion 2018.x

### ISSUE THREAD

**Issue by koldoon** [kropp/intellij-qml#4]
Only key words are colored, but the other tokens - not, although their configuration does present in code style settings: Type names,  id's, attributes - all the same.

**Comment by machinekoder** [comment]
Well, it actually highlights something. The bigger problem is that automatic code indentation does not work.

**Comment by machinekoder** [comment]
I'm willing to pay someone to fix this: https://www.upwork.com/ab/applicants/1010187982090784768/job-details
